var DemandDepositData = {
    CHQ_SLIP_TRANS_FLAG: null,
    CHQ_SLIP_TRANS_FLAG_CSH: null,
    CHQ_SLIP_TRANS_FLAG_TRF: null,
    STI_FLAG: null,
    SWP_IN_FLAG: null,
    SWP_OUT_FLAG: null,
    RSTC_CLG_DR: null,
    RSTC_CSH_DR: null,
    RSTC_CLG_CR: null,
    RSTC_TRF_DR: null,
    RSTC_CSH_CR: null,
    RSTC_TRF_CR: null,
    REMOTE_FLAG_DR: null,
    REMOTE_FLAG_CR: null,
    AVAIL_BALANCE: null,
    LIST_RTL_ACC_DOC: [],
    ACC_TITLE: null,
    CURR_SH_NAME: null,
    ROWID: null,
    TRACKING_ID: null,
    NFT_LOG_MSG: null,
    ERROR_MSG: null,
    LIST_SMS_NFT_AUTHORZ_LOG: [],
    LIST_RTL_ACC_MANDATE: [],
    LIST_RTL_ACC_KYC: [],
    LIST_RTL_TRANS_CONDITION: [],
    PRODUCT_NM: null,
    SHORT_NM: null,
    CUSTOMER_FULL_NM: null,
    GROUP_NM: null,
    YTD_INTEREST_PAID: null,
    LST_INT_APPLY_AMOUNT_CR: null,
    LST_INT_APPLY_AMOUNT_DR: null,
    INT_CAL_OFF: null,
    NO_INT_CAL_CR: null,
    NOTICE_APPLICABLE: null,
    CHK_WITHDRAWAL_NO: null,
    CHK_WITHDRAWAL_AMT: null,
    CHK_PENAL_INT: null,
    STATE_CYCLE: null,
    LST_STATE_GEN_DT: null,
    SBS_SECTOR_ID: null,
    SBS_SECURITY_ID: null,
    SBS_ECO_PUR_ID: null,
    SBS_DEPO_ID: null,
    AUTH_STATUS_ID: null,
    MAKE_BY: null,
    MAKE_DT: null,
    AUTH_1ST_BY: null,
    AUTH_1ST_DT: null,
    AUTH_2ND_BY: null,
    AUTH_2ND_DT: null,
    LAST_ACTION: null,
    FUTURE_AMOUNT: null,
    OACCOUNT_NUMBER: null,
    AVG_BAL_CAL_DT: null,
    KYC_FLAG: null,
    ATM_FLAG: null,
    RO_EMP_ID: null,
    BRANCH_ID: null,
    ACCOUNT_NUMBER: null,
    CHK_DIGIT: null,
    PRODUCT_ID: null,
    PROD_TYPE: null,
    CURR_ID: null,
    JOINT_ACC_FLAG: null,
    INTRO_ACC_FLAG: null,
    ACC_TYPE: null,
    GROUP_ID: null,
    CUSTOMER_ID: null,
    ACC_STATUS: null,
    STATUS_DT: null,
    SPECIAL_INST: null,
    ACC_OPEN_DT: null,
    LST_INT_CAL_DT_CR: null,
    LST_INT_APPLY_DT_CR: null,
    NEXT_INT_APPLY_DT_CR: null,
    LST_TRN_DT: null,
    MAIL_ADDRS: null,
    PROD_CAL: null,
    PROD_CAL_ON_BAL: null,
    PROD_CAL_ON_CR: null,
    INT_RATE_ID: null,
    PROD_POS_INT_CR_VARI: null,
    PROD_NEG_INT_CR_VARI: null,
    PROD_INT_TOT_CR: null,
    PROD_INT_TOT_CR1: null,
    CR_PROD_CAPT_FREQ: null,
    CURRENT_BALANCE_LCY: null,
    CURRENT_BALANCE_CCY: null,
    BALANCE_LCY: null,
    BALANCE_CCY: null,
    OPENING_BALANCE_LCY: null,
    OPENING_BALANCE_CCY: null,
    CLOSING_BALANCE_LCY: null,
    CLOSING_BALANCE_CCY: null,
    CLG_AMOUNT: null,
    LIEN_AMOUNT: null,
    BLOCKED_AMOUNT: null,
    HOLD_AMOUNT: null,
    SWP_IN_AMOUNT: null,
    PEND_AUTH_DR: null,
    PEND_AUTH_CR: null,
    INT_CAL_BALANCE: null,
    WITHHELD_INTEREST: null,
    FLOATING_AMOUNT: null,
    INT_ACCRUED_TO_MONTH_CR: null,
    ACCUMULATED_INTEREST_CR: null,
    INTEREST_PAYABLE_CR: null,
    ACC_STATUS_NM: null,
    SYS_PROC_EXCP: null,
    CREATE_BY: null,
    CREATE_DT: null,
    DEBIT_CARD_NO: null,
    CALL_CENTER_FLAG: null,
    INT_RATE_FIXED: null,
    CENTER_ID: null,
    CENTER_NM: null,
    IB_REGISTER_FLAG: null,
    SUB_ADDR_ID: null,
    IB_FUND_TRANS_FLAG: null,
    PFT_SHR_RATIO: null,
    SMS_ALART_SERVICE_FLAG: null,
    EMAIL_ALART_SERVICE_FLAG: null,
    REF_BRANCH_ID: null,
    REF_ACCOUNT_NO: null,
    LIEN_TYPE: null,
    LIST_COR_RO_ACC_LOG: [],
    LIST_COR_RO_LOG: [],
    counter: null,
    CloneObj: null,
    isAdd: null,
    isDelete: null,
    isOld: null,
    CreateByLoginId: null,
    MakeByLoginId: null,
    AuthByLoginId: null,
};

const state = {
  DemandDepositData: { ...DemandDepositData },
};
const getters = {
};
const mutations = {
  setDemandDeposit(state, DemandDepositData) {
   // console.log("from set DemandDeposit");
  //  console.log(DemandDepositData);
    state.DemandDepositData = DemandDepositData;
  },
  resetDemandDeposit(state) {
   // console.log("from reset");
    state.DemandDepositData = { ...DemandDepositData };
  },
};
const actions = {
};
export default {
  state,
  getters,
  actions,
  mutations,
};
