var EnquiryData = {
  CENTER_ID: null,
  CENTER_NM: null,
  AVAIL_BALANCE: null,
  LIST_RTL_ACC_DOC: [],
  LIST_RTL_TERM_INS_STATUS: [],
  ROWID: null,
  TRACKING_ID: null,
  NFT_LOG_MSG: null,
  ERROR_MSG: null,
  LIST_SMS_NFT_AUTHORZ_LOG: [],
  LIST_RTL_TRANS_CONDITION: [],
  LIST_RTL_ACC_MANDATE: [],
  PRODUCT_NM: null,
  SHORT_NM: null,
  CUSTOMER_FULL_NM: null,
  GROUP_NM: null,
  CURRENCY_SH_NM: null,
  DECEASED_ACC: null,
  AUTH_1ST_DT: null,
  AUTH_2ND_BY: null,
  AUTH_2ND_DT: null,
  LAST_ACTION: null,
  PAY_IN_TRF_BR_ID: null,
  PAY_OUT_PRIN_BR_ID: null,
  PAY_OUT_INT_BR_ID: null,
  PAY_OUT_PRIN_CSH: null,
  PAY_OUT_INT_CSH: null,
  AUTO_RENEW_FIXED_PRIN: null,
  RO_EMP_ID: null,
  INT_PAYABLE_NO: null,
  INT_PAYABLE_FREQ: null,
  CR_PROD_CAPT_FREQ: null,
  MAT_DT_CAL_METHOD: null,
  MAT_DT_CAL_FREQ: null,
  MAT_DUE_NOTICE_DAY: null,
  UNCLAIM_DEPO_TERM: null,
  UNCLAIM_DEPO_TERM_FREQ: null,
  DORM_TRANS_PREIOD: null,
  DORM_TRANS_PREIOD_FREQ: null,
  AFT_MAT_DEPO: null,
  MATU_AUTO_RENEW: null,
  RENEWAL_INST: null,
  INS_AUTO_RENEW: null,
  INS_AUTO_RENEW_RT: null,
  INS_MAX_AUTO_RENEW_NO: null,
  NOINS_AUTO_RENEW: null,
  NOINST_ACC_PREFIX: null,
  NOINS_AUTO_RENEW_TERM: null,
  NOINS_AUTO_RENEW_RT: null,
  NOINS_MAX_AUTO_RENEW_NO: null,
  LST_INT_CAL_DT_CR: null,
  LST_INT_APPLY_DT_CR: null,
  NEXT_INT_APPLY_DT_CR: null,
  LST_TRN_DT: null,
  LST_ANNIVERSARY_DT: null,
  LST_PAYABLE_DT: null,
  INT_RATE_ID: null,
  PROD_POS_INT_CR_VARI: null,
  PROD_NEG_INT_CR_VARI: null,
  PROD_INT_TOT_CR: null,
  CURRENT_BALANCE_LCY: null,
  CURRENT_BALANCE_CCY: null,
  BALANCE_LCY: null,
  BALANCE_CCY: null,
  OPENING_BALANCE_LCY: null,
  OPENING_BALANCE_CCY: null,
  CLOSING_BALANCE_LCY: null,
  CLOSING_BALANCE_CCY: null,
  MIN_BALANCE_REQ: null,
  CLG_AMOUNT: null,
  LIEN_AMOUNT: null,
  BLOCKED_AMOUNT: null,
  HOLD_AMOUNT: null,
  SWP_IN_AMOUNT: null,
  PEND_AUTH_DR: null,
  PEND_AUTH_CR: null,
  INT_CAL_BALANCE: null,
  WITHHELD_INTEREST: null,
  FLOATING_AMOUNT: null,
  FUTURE_AMOUNT: null,
  INT_ACCRUED_TO_MONTH_CR: null,
  ACCUMULATED_INTEREST_CR: null,
  INTEREST_PAYABLE_CR: null,
  YTD_INTEREST_EARN: null,
  YTD_INTEREST_PAID: null,
  LST_INT_APPLY_AMOUNT_CR: null,
  INT_CAL_ON: null,
  NO_INT_CAL_CR: 0,
  STATE_CYCLE: null,
  LST_STATE_GEN_DT: null,
  ENCASH: null,
  FULL_ENCASH: null,
  PART_ENCASH: null,
  PAY_IN_FLAG: null,
  PAY_IN_TRF_ACNO: null,
  PAY_OUT_PRIN_TRN: null,
  PAY_OUT_PRIN_ACNO: null,
  PAY_OUT_INT_TRN: null,
  PAY_OUT_INT_ACNO: null,
  PAY_OUT_PRIN_SUND_ACC: null,
  PAY_OUT_PRIN_BANKERS_CHQ_ACC: null,
  PAY_OUT_INT_SUND_ACC: null,
  PAY_OUT_INT_BANKERS_CHQ_ACC: null,
  PRINCIPAL_CR_FLAG: null,
  RESTRICT_CSH_DR: null,
  RESTRICT_CLG_CR: null,
  RESTRICT_TRF_DR: null,
  RESTRICT_CSH_CR: null,
  RESTRICT_TRF_CR: null,
  REMOTE_FLAG_DR: null,
  REMOTE_FLAG_CR: null,
  DECEASED_DT: null,
  SBS_SECURITY_ID: null,
  SBS_ECO_PUR_ID: null,
  SBS_PRIVLGE_ID: null,
  OACCOUNT_NUMBER: null,
  AUTH_STATUS_ID: null,
  MAKE_BY: null,
  MAKE_DT: null,
  AUTH_1ST_BY: null,
  BRANCH_ID: null,
  ACCOUNT_NUMBER: null,
  CHK_DIGIT: null,
  PRODUCT_ID: null,
  PROD_TYPE: null,
  CURR_ID: null,
  CURR_TYPE: null,
  ACC_TYPE: null,
  ACC_TITLE: null,
  GROUP_ID: null,
  CUSTOMER_ID: null,
  ACC_STATUS: null,
  SPECIAL_INST: null,
  JOINT_ACC_HOLDER: null,
  ACC_OPEN_DT: null,
  TOT_TERM_NO: null,
  TOT_TERM_FREQ: null,
  TOT_TERM_PAID: null,
  ACC_RENEWAL_DT: null,
  MATURITY_DT: null,
  PRINCIPAL_AMT: null,
  MATURITY_AMT: null,
  BONUS_AMT: null,
  PENAL_AMT_ENCASH: null,
  INSTRUMENT_NO: null,
  MAIL_ADDRS: null,
  PROD_CAL: null,
  PROD_CAL_ON_CR: null,
  PROD_CAL_ON_BAL: null,
  INT_PAYABLE_FLAG: null,
  ACC_STATUS_NM: null,
  SBS_SECTOR_ID: null,
  REF_BRANCH_ID: null,
  REF_ACCOUNT_NO: null,
  LIEN_TYPE: null,
  CURR_SH_NAME: null,
  INSTRUMENT_PREFIX: null,
  PRINCIPAL_AMT_RENEW: null,
  SYS_PROC_EXCP: null,
  CREATE_BY: null,
  CREATE_DT: null,
  CALL_CENTER_FLAG: null,
  LIST_COR_RO_ACC_LOG: [],
  LIST_COR_RO_LOG: [],
  STATUS_DT: null,
  SUB_ADDR_ID: null,
  PFT_SHR_RATIO: null,
  SMS_ALART_SERVICE_FLAG: null,
  EMAIL_ALART_SERVICE_FLAG: null,
  WALLET_SRV_PROVIDER_ID: null,
  WALLET_NUMBER: null,
  CloneObj: null,
  isAdd: null,
  isDelete: null,
  isOld: null,
  CreateByLoginId: null,
  MakeByLoginId: null,
  AuthByLoginId: null,
};
var EnquiryDataSCM = {
  CENTER_ID: null,
  CENTER_NM: null,
  AVAIL_BALANCE: null,
  LIST_RTL_ACC_DOC: [],
  LIST_RTL_TERM_INS_STATUS: [],
  ROWID: null,
  TRACKING_ID: null,
  NFT_LOG_MSG: null,
  ERROR_MSG: null,
  LIST_SMS_NFT_AUTHORZ_LOG: [],
  LIST_RTL_TRANS_CONDITION: [],
  LIST_RTL_ACC_MANDATE: [],
  PRODUCT_NM: null,
  SHORT_NM: null,
  CUSTOMER_FULL_NM: null,
  GROUP_NM: null,
  CURRENCY_SH_NM: null,
  DECEASED_ACC: null,
  AUTH_1ST_DT: null,
  AUTH_2ND_BY: null,
  AUTH_2ND_DT: null,
  LAST_ACTION: null,
  PAY_IN_TRF_BR_ID: null,
  PAY_OUT_PRIN_BR_ID: null,
  PAY_OUT_INT_BR_ID: null,
  PAY_OUT_PRIN_CSH: null,
  PAY_OUT_INT_CSH: null,
  AUTO_RENEW_FIXED_PRIN: null,
  RO_EMP_ID: null,
  INT_PAYABLE_NO: null,
  INT_PAYABLE_FREQ: null,
  CR_PROD_CAPT_FREQ: null,
  MAT_DT_CAL_METHOD: null,
  MAT_DT_CAL_FREQ: null,
  MAT_DUE_NOTICE_DAY: null,
  UNCLAIM_DEPO_TERM: null,
  UNCLAIM_DEPO_TERM_FREQ: null,
  DORM_TRANS_PREIOD: null,
  DORM_TRANS_PREIOD_FREQ: null,
  AFT_MAT_DEPO: null,
  MATU_AUTO_RENEW: null,
  RENEWAL_INST: null,
  INS_AUTO_RENEW: null,
  INS_AUTO_RENEW_RT: null,
  INS_MAX_AUTO_RENEW_NO: null,
  NOINS_AUTO_RENEW: null,
  NOINST_ACC_PREFIX: null,
  NOINS_AUTO_RENEW_TERM: null,
  NOINS_AUTO_RENEW_RT: null,
  NOINS_MAX_AUTO_RENEW_NO: null,
  LST_INT_CAL_DT_CR: null,
  LST_INT_APPLY_DT_CR: null,
  NEXT_INT_APPLY_DT_CR: null,
  LST_TRN_DT: null,
  LST_ANNIVERSARY_DT: null,
  LST_PAYABLE_DT: null,
  INT_RATE_ID: null,
  PROD_POS_INT_CR_VARI: null,
  PROD_NEG_INT_CR_VARI: null,
  PROD_INT_TOT_CR: null,
  CURRENT_BALANCE_LCY: null,
  CURRENT_BALANCE_CCY: null,
  BALANCE_LCY: null,
  BALANCE_CCY: null,
  OPENING_BALANCE_LCY: null,
  OPENING_BALANCE_CCY: null,
  CLOSING_BALANCE_LCY: null,
  CLOSING_BALANCE_CCY: null,
  MIN_BALANCE_REQ: null,
  CLG_AMOUNT: null,
  LIEN_AMOUNT: null,
  BLOCKED_AMOUNT: null,
  HOLD_AMOUNT: null,
  SWP_IN_AMOUNT: null,
  PEND_AUTH_DR: null,
  PEND_AUTH_CR: null,
  INT_CAL_BALANCE: null,
  WITHHELD_INTEREST: null,
  FLOATING_AMOUNT: null,
  FUTURE_AMOUNT: null,
  INT_ACCRUED_TO_MONTH_CR: null,
  ACCUMULATED_INTEREST_CR: null,
  INTEREST_PAYABLE_CR: null,
  YTD_INTEREST_EARN: null,
  YTD_INTEREST_PAID: null,
  LST_INT_APPLY_AMOUNT_CR: null,
  INT_CAL_ON: null,
  NO_INT_CAL_CR: 0,
  STATE_CYCLE: null,
  LST_STATE_GEN_DT: null,
  ENCASH: null,
  FULL_ENCASH: null,
  PART_ENCASH: null,
  PAY_IN_FLAG: null,
  PAY_IN_TRF_ACNO: null,
  PAY_OUT_PRIN_TRN: null,
  PAY_OUT_PRIN_ACNO: null,
  PAY_OUT_INT_TRN: null,
  PAY_OUT_INT_ACNO: null,
  PAY_OUT_PRIN_SUND_ACC: null,
  PAY_OUT_PRIN_BANKERS_CHQ_ACC: null,
  PAY_OUT_INT_SUND_ACC: null,
  PAY_OUT_INT_BANKERS_CHQ_ACC: null,
  PRINCIPAL_CR_FLAG: null,
  RESTRICT_CSH_DR: null,
  RESTRICT_CLG_CR: null,
  RESTRICT_TRF_DR: null,
  RESTRICT_CSH_CR: null,
  RESTRICT_TRF_CR: null,
  REMOTE_FLAG_DR: null,
  REMOTE_FLAG_CR: null,
  DECEASED_DT: null,
  SBS_SECURITY_ID: null,
  SBS_ECO_PUR_ID: null,
  SBS_PRIVLGE_ID: null,
  OACCOUNT_NUMBER: null,
  AUTH_STATUS_ID: null,
  MAKE_BY: null,
  MAKE_DT: null,
  AUTH_1ST_BY: null,
  BRANCH_ID: null,
  ACCOUNT_NUMBER: null,
  CHK_DIGIT: null,
  PRODUCT_ID: null,
  PROD_TYPE: null,
  CURR_ID: null,
  CURR_TYPE: null,
  ACC_TYPE: null,
  ACC_TITLE: null,
  GROUP_ID: null,
  CUSTOMER_ID: null,
  ACC_STATUS: null,
  SPECIAL_INST: null,
  JOINT_ACC_HOLDER: null,
  ACC_OPEN_DT: null,
  TOT_TERM_NO: null,
  TOT_TERM_FREQ: null,
  TOT_TERM_PAID: null,
  ACC_RENEWAL_DT: null,
  MATURITY_DT: null,
  PRINCIPAL_AMT: null,
  MATURITY_AMT: null,
  BONUS_AMT: null,
  PENAL_AMT_ENCASH: null,
  INSTRUMENT_NO: null,
  MAIL_ADDRS: null,
  PROD_CAL: null,
  PROD_CAL_ON_CR: null,
  PROD_CAL_ON_BAL: null,
  INT_PAYABLE_FLAG: null,
  ACC_STATUS_NM: null,
  SBS_SECTOR_ID: null,
  REF_BRANCH_ID: null,
  REF_ACCOUNT_NO: null,
  LIEN_TYPE: null,
  CURR_SH_NAME: null,
  INSTRUMENT_PREFIX: null,
  PRINCIPAL_AMT_RENEW: null,
  SYS_PROC_EXCP: null,
  CREATE_BY: null,
  CREATE_DT: null,
  CALL_CENTER_FLAG: null,
  LIST_COR_RO_ACC_LOG: [],
  LIST_COR_RO_LOG: [],
  STATUS_DT: null,
  SUB_ADDR_ID: null,
  PFT_SHR_RATIO: null,
  SMS_ALART_SERVICE_FLAG: null,
  EMAIL_ALART_SERVICE_FLAG: null,
  WALLET_SRV_PROVIDER_ID: null,
  WALLET_NUMBER: null,
  CloneObj: null,
  isAdd: null,
  isDelete: null,
  isOld: null,
  CreateByLoginId: null,
  MakeByLoginId: null,
  AuthByLoginId: null,
};

var EnquiryDataCredit = {
  CCS_CODE: null,
  CARD_PA_NO: null,
  CARD_AC_NO: null,
  CARD_PA_TITLE: null,
  CARD_LIMIT_AMT_LCY: null,
  CARD_LIMIT_AMT_CCY: null,
  EXPIRY_DT: null,
  BANK_BR_ID: null,
  BANK_ACC_NO: null,
  PHONE: null,
  DATE_OF_BIRTH: null,

}

var EnquiryDataGovt = {
  REG_NO: null,
  PRODUCT_NAME: null,
  CURRENCY_CODE: null,
  EXCHANGE_RATE: null,
  CUSTOMER_ID: null,
  REG_DATE: null,
  MATURITY_DT: null,
  INT_CAPT_FREQ_FULL_NAME: null,
  AMOUNT_LCY: null,
  AMOUNT_CCY: null,
  NOMI_NAME: null,
}

var EnquiryDataGuarantee = {
  GUARANTEE_ID: null,
  ISSUE_DATE: null,
  GUR_PRD_NM: null,
  EFFECT_DATE: null,
  CURRENCY_SH_NM: null,
  GUR_TYPE_NM: null,
  EXP_DATE: null,
  ISSUED_AMOUNT_CCY: null,
  APPL_CUST_ID: null,
  APPL_CUST_GRP_ID: null,
  ISSUED_AMOUNT_LCY: null,
  COMMIT_ID: null,
  APPL_CUST_ADDR1: null,
  APPL_CUST_COUNTRY_NM: null,
  BENF_NAME: null,
  BENF_CUST_ADD: null,
  BENF_CUST_COUNTRY_NM: null,
  REFUNDED_MARGIN_AMT: null,
  MARGIN_PAID_AMT: null,
  ISSUED_AMOUNT_LCY: null,
  SECURITY_TYPE: null,
}

var EnquiryDataImport = {
  LC_BRANCH_ID: null,
  LC_YEAR: null,
  LC_PRD_TYPE: null,
  LC_SERIAL: null,
  PRODUCT_ID: null,
  PROPOSAL_ID: null,
  LC_AMEND_NO: null,
  LC_AMEND_DT: null,
  CREDIT_LINE_ID: null,
  COMMIT_ID: null,
  LC_PAY_MODE: null,
  BENF_CODE: null,
  ECO_PURPOSE_CODE: null,
  LCAF_NO: null,
  TENOR_PERIOD: null,
  TRANSMIT_MODE_CODE: null,
  TRANSMIT_MODE: null,
  SHIPPING_MARKS: null,
  CURRENCY_SH_NM: null,
  EXC_RATE_ID: null,
  EXC_RATE: null,
  LC_AMOUNT_CCY: null,
  LC_AMOUNT_LCY: null,
  LIABILITY_ISSUED: null,
  LIABILITY_REVERSED: null,
  MARGIN_PCT: null,
  MARGIN_AMOUNT_LCY: null,
  PAID_MARGIN_PCT: null,
  PAID_MARGIN_AMOUNT_LCY: null,
  REFUNDED_MARGIN_LCY: null,
  BILL_AMOUNT_CCY: null,
  BILL_AMOUNT_LCY: null,
  EXEC_DATE: null,
  SHIPMENT_DT: null,
  EXPIRY_DT: null,
}

var EnquiryDataExport = {
  LC_BRANCH_ID: null,
  EXP_LC_NO: null,
  PRODUCT_ID: null,
  ADVICE_YEAR: null,
  ADVICE_SL: null,
  LC_AMEND_NO: null,
  LC_AMEND_DT: null,
  CUST_AC_NO: null,
  LC_PAY_MODE: null,
  TENOR_PERIOD: null,
  APPLICANT_NAME: null,
  APPLICANT_ADDRS: null,
  BENF_NAME: null,
  BENF_ADDRS: null,
  EXPORT_FILE_NO: null,
  LC_AMOUNT_CCY: null,
  LC_AMOUNT_LCY: null,
  BILL_AMOUNT_CCY: null,
  BILL_AMOUNT_LCY: null,
  EXEC_DATE: null,
  SHIPMENT_DT: null,
  EXPIRY_DT: null,
 
}
var EnquiryDataExport = {
  LC_BRANCH_ID: null,
  EXP_LC_NO: null,
  PRODUCT_ID: null,
  ADVICE_YEAR: null,
  ADVICE_SL: null,
  LC_AMEND_NO: null,
  LC_AMEND_DT: null,
  CUST_AC_NO: null,
  LC_PAY_MODE: null,
  TENOR_PERIOD: null,
  APPLICANT_NAME: null,
  APPLICANT_ADDRS: null,
  BENF_NAME: null,
  BENF_ADDRS: null,
  EXPORT_FILE_NO: null,
  LC_AMOUNT_CCY: null,
  LC_AMOUNT_LCY: null,
  BILL_AMOUNT_CCY: null,
  BILL_AMOUNT_LCY: null,
  EXEC_DATE: null,
  SHIPMENT_DT: null,
  EXPIRY_DT: null,
 
}

const state = {
  EnquiryDataInfo: { ...EnquiryData },
  EnquiryDataInfoSCM: { ...EnquiryDataSCM },
  EnquiryDataInfoCredit: { ...EnquiryDataCredit },
  EnquiryDataInfoGovt: { ...EnquiryDataGovt },
  EnquiryDataInfoGuarantee: { ...EnquiryDataGuarantee },
  EnquiryDataInfoImport: { ...EnquiryDataImport },
  EnquiryDataInfoExport: { ...EnquiryDataExport },
};

const getters = {
};

const mutations = {
  setEnquiryDataInfo(state, EnquiryDataInfo) {
   // console.log("from set");
   // console.log(EnquiryDataInfo);
    state.EnquiryDataInfo = EnquiryDataInfo;
  },
  resetsetEnquiryDataInfo(state) {
   // console.log("from reset");
    state.EnquiryDataInfo = { ...EnquiryDataInfo };
  },
  setEnquiryDataInfoSCM(state, EnquiryDataInfoSCM) {
   // console.log("from set scm");
    console.log(EnquiryDataInfoSCM);
    state.EnquiryDataInfoSCM = EnquiryDataInfoSCM;
  },
  resetEnquiryDataInfoSCM(state) {
   // console.log("from reset");
    state.EnquiryDataInfoSCM = { ...EnquiryDataInfoSCM };
  },

  setEnquiryDataInfoCredit(state, EnquiryDataInfoCredit) {
  //  console.log("from set scm");
  //  console.log(EnquiryDataInfoCredit);
    state.EnquiryDataInfoCredit = EnquiryDataInfoCredit;
  },
  resetEnquiryDataInfoCredit(state) {
   // console.log("from reset");
    state.EnquiryDataInfoCredit = { ...EnquiryDataInfoCredit };
  },

  setEnquiryDataInfoGovt(state, EnquiryDataInfoGovt) {
  //  console.log("from set scm");
  //  console.log(EnquiryDataInfoGovt);
    state.EnquiryDataInfoGovt = EnquiryDataInfoGovt;
  },
  resetEnquiryDataInfoGovt(state) {
  //  console.log("from reset");
    state.EnquiryDataInfoGovt = { ...EnquiryDataInfoGovt };
  },

  setEnquiryDataInfoGuarantee(state, EnquiryDataInfoGuarantee) {
  //  console.log("from set scm");
  //  console.log(EnquiryDataInfoGuarantee);
    state.EnquiryDataInfoGuarantee = EnquiryDataInfoGuarantee;
  },
  resetEnquiryDataInfoGuarantee(state) {
   // console.log("from reset");
    state.EnquiryDataInfoGuarantee = { ...EnquiryDataInfoGuarantee };
  },

  setEnquiryDataInfoImport(state, EnquiryDataInfoImport) {
  //  console.log("from set scm");
  //  console.log(EnquiryDataInfoImport);
    state.EnquiryDataInfoImport = EnquiryDataInfoImport;
  },
  resetEnquiryDataInfoImport(state) {
  //  console.log("from reset");
    state.EnquiryDataInfoImport = { ...EnquiryDataInfoImport };
  },

  setEnquiryDataInfoExport(state, EnquiryDataInfoExport) {
   // console.log("from set scm");
 //   console.log(EnquiryDataInfoExport);
    state.EnquiryDataInfoExport = EnquiryDataInfoExport;
  },
  resetEnquiryDataInfoExport(state) {
  //  console.log("from reset");
    state.EnquiryDataInfoExport = { ...EnquiryDataInfoExport };
  },



  // 
  // 
  // setOtherInfo(
  //   state,
  //   { MAKE_BY, MAKE_DT, AUTH_1ST_BY, AUTH_1ST_DT, LAST_ACTION }
  // ) {},
};

const actions = {
  // changeCustomer (context, payload) {
  //     setTimeout(() => {
  //       context.commit(changeCustomer, payload);
  //     }, 2000);
  //   }
};

export default {
  state,
  getters,
  actions,
  mutations,
};
