
var customerInfoData = {
    customerProfileData: {  
        CUSTOMER_ID: null,
        CUSTOMER_CATEGORY_ID: null,
        CUSTOMER_CATEGORY_NM: null,
        CUSTOMER_TYPE_ID: null,
        CUSTOMER_FULL_NM: null,
        CUSTOMER_SHORT_NM: null,
        CUSTOMER_SALUTATION: null,
        CUSTOMER_FIRST_NM: null,
        CUSTOMER_MIDDLE_NM: null,
        CUSTOMER_LAST_NM: null,
        NO_MIDDLE_NM_FLAG: null,
        NO_LAST_NM_FLAG: null,
        CUSTOMER_IC_TYPE_ID: null,
        CUSTOMER_IC: null,
        CUSTOMER_CONCENTRATION_ID: null,
        CUSTOMER_CONCENTRATION_NM: null,
        OWNERSHIP_TYPE_ID_CTR: null,
        OWNERSHIP_TYPE_ID_CIB: null,
        HOME_BRANCH_ID: null,
        HOME_BRANCH_NM: null,
        SECTOR_SBS_ID: null,
        SECTOR_SBS_NM: null,
        SECTOR_CIB_ID: null,
        SECTOR_CIB_NM: null,
        SECTOR_TYPE_ID: null,
        INTRODUCER_TYPE_ID: null,
        INTRODUCER_ACC_BRANCH_ID: null,
        INTRODUCER_ACC_BRANCH_NM: null,
        INTRODUCER_ACC_NO: null,
        INTRODUCER_ACC_NM: null,
        INTRODUCER_EMP_ID: null,
        INTRODUCER_EMP_NM: null,
        INTRODUCER_EMP_PA_NO: null,
        INTRODUCER_DESCRIP: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        LAST_ACTION: null,
        ROWID: null,
        TRACKING_ID: null,
        NFT_LOG_MSG: null,
        ERROR_MSG: null,
        LIST_SMS_NFT_AUTHORZ_LOG: null,
        OBJ_COR_CUS_INDIVIDUAL: null,
        OBJ_COR_CUS_PERM_ADDR: null,
        OBJ_COR_CUS_RES_ADDR: null,
        OBJ_COR_CUS_CURRENT_LINE: null,
        OBJ_COR_CUS_PREVIOUS_LINE: null,
        OBJ_COR_CUS_PARENT_INFO: null,
        OBJ_COR_CUS_SPOUSE_INFO: null,
        OBJ_COR_CUS_ORGANIZATION: null,
        OBJ_COR_CUS_BUS_ADDR: null,
        OBJ_COR_CUS_TRADE_INFO: null,
        OBJ_COR_CUS_TRADE_BANK_INFO: null,
        OBJ_COR_CUS_FAC_ADDR: null,
        OBJ_COR_CUS_OWNER_INFO: null,
        OBJ_COR_CUS_RISK_RATING: {},
        OBJ_COR_CUS_MASTER_AC: null,
        OBJ_COR_CUS_ASSOCI_AC: null,
        OBJ_COR_CUS_KYC: null,
        LIST_SMS_NFT_AUTHORZ_LOG_OWNER_INFO: [],
        LIST_COR_CUS_OWNER_INFO: [],
        LIST_COR_CUS_TRADE_BANK_INFO: [],
        LIST_SMS_NFT_AUTHORZ_LOG_LIEN_BANK: [],
        LIST_SMS_NFT_AUTHORZ_LOG_ASSOCI_AC: [],
        LIST_COR_CUS_ASSOCI_AC: [],
        LIST_COR_CUS_DOCUMENT: [],
        LIST_COR_CUS_ADDRESS: [],
        LIST_COR_CUS_OCCUPATION: [],
        LIST_COR_CUS_SUB_ADDRESS: [], 
        LIST_COR_CUS_FAC_ADDR: [],
        BIRTH_DATE: null,
        NATIONAL_ID: null,
        PASSPORT_NO: null,
        TIN_NO: null,
        FATHER_NM: null,
        MOTHER_NM: null,
        SPOUSE_NM: null,
        BRANCH_NM: null,
        CUSTOMER_IC_TYPE_NM: null,
        ADDRESS_TYPE: null,
        ADDRESS1: null,
        ADDRESS2: null,
        CITY: null,
        ZIP_CODE: null,
        THANA: null,
        DISTRICT: null,
        COUNTRY: null,
        DIVISION: null,
        PHONE: null,
        MOBILE: null,
        TELEX: null,
        FAX: null,
        SWIFT: null,
        EMAIL: null,
        WEB: null,
        ORG_REGESTRATION_NO: null,
        ORG_REGESTRATION_DATE: null,
        ORG_REGESTRATION_PLACE: null,
        ORG_TIN: null,
        ORG_BIN: null,
        ORG_VAT_REG_NO: null,
        NATURE_OF_BUSINESS_KYC: null,
        HOW_CUSTOMER_INTRODUCE: null,
        NET_WORTH_ID: null,
        CUS_OPEN_NATURE_ID: null,
        PROFESSION_ID: null,
        TRAD_LICENSE_NO: null,
        CB_ORG_TYPE_ID: null,
        COUNTRY_CODE: null,
        DIVISION_CODE: null,
        DISTRICT_CODE: null,
        THANA_CODE: null,
        SECTOR_NDBC_ID: null,
        SECTOR_NDBC_NM: null,
        CENTER_ID: null,
        SUBMITTED_BY: null,
        ALIAS_NAME1: null,
        ALIAS_NAME2: null,
        LON_FINANCE_SECTOR_ID: null,
        LON_FINANCE_SECTOR_NM: null,
        SDN_FLAG: null,
        CREATE_BY: null,
        CREATE_DT: null,
        IS_ADDR_VERIFIED: null,
        TOTAL_RATING: null,
        HOW_ADDR_VERIFIED: null,
        IS_PEP: null,
        IS_APPR_SR_MGT: null,
        SOURCE_OF_WEALTH: null,
        IS_INTERVIEW_TAKEN: null,
        CUS_GRP_TYPE: null,
        APPROVED_BY: null,
        INTERVIEWED_BY: null,
        NBR_CATEGORY_ID: null,
        CUS_STATUS: null,
        CUS_STATUS_CHANGE_DT: null,
        PROSPECTIVE_CUSTOMER_ID: null,
        IS_IPS: null,
        IS_CIOS: null,
        KYC_OTHER_DTL: null,
        KYC_OTHER_RATING: null,
        CUSTOMER_ID_EXCEL: null,
    },
    customerOrgData:{
        NET_WORTH: null,
        RESERVE_CAPITAL: null,
        AUDITOR_COMPANY: null,
        IS_FINANCIAL_INST_FLAG: null,
        FIN_INSTITUTE_TYPE_ID: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        LAST_ACTION: null,
        CUSTOMER_ID: null,
        CUSTOMER_NM: null,
        ESTABLISHMENT_DT: null,
        NATURE_OF_BUSINESS: null,
        NO_OF_YEAR_BUSINESS: null,
        CONSTITUENT_TYPE_ID: null,
        REGISTRATION_NO: null,
        REGISTRATION_DT: null,
        REGISTRATION_AUTHORITY: null,
        REGISTRATION_AUTH_ID: null,
        REGISTRATION_PLACE: null,
        AUTHORIZED_CAPITAL: null,
        PAIDUP_CAPITAL: null,
        NFT_LOG_MSG: null,
        ROWID: null,
        TRACKING_ID: null,
        COMMENCEMENT_DT: null,
        COMMERCIAL_PRODUCTION_DT: null,
        DAILY_PRODUCTION_CAPACITY: null,
        ACTUAL_PRODUCTION_CAPACITY: null,
        NO_OF_EMPLOYEE: null,
        NO_OF_LABOR: null,
        ORG_NATURE_OF_BUSINESS_SOURCE_OF_FUND: null,
        SOURCE_FUND_DESC: null,
        TIN_NO: null,
        BIN_NO: null,
        VAT_REGISTRATION_NO: null,
        BUSINESS_CATEGORY_ID: null,
        REMARKS: null,
        NO_OF_EMPLOYEE_M: null,
        NO_OF_EMPLOYEE_F: null,  
        BOI_REG_NUMBER: null,  
        INCORPORATION_NO: null,  
        organization_type_id: null
    },
    customerTradeInfo: {
        TIN_NO: null,
        BIN_NO: null,
        VAT_REGISTRATION_NO: null,
        VAT_REGISTRATION_DT: null,
        IMPORTER_FLAG: null,
        IMPORTER_TYPE_LGID: null,
        IRC_TYPE_LGID: null,
        IRC_LIMIT: null,
        IRC_EXP_DT: null,
        IRC_TREASURY_CHALLAN_NO: null,
        IRC_TREASURY_CHALLAN_DT: null,
        EXPORTER_FLAG: null,
        ERC_LIMIT: null,
        ERC_EXP_DT: null,
        ERC_TREASURY_CHALLAN_NO: null,
        ERC_TREASURY_CHALLAN_DT: null,
        EXPORT_QUOTA_FLAG: null,
        EXPORT_QUOTA_DESCRIP: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        AUTH_STATUS_ID: null,
        LAST_ACTION: null,
        CUSTOMER_ID: null,
        CUSTOMER_NM: null,
        TRADE_LICENSE_NO: null,
        TRADE_LICENSE_ISSUE_DT: null,
        TRADE_LICENSE_EXP_DT: null,
        ROWID: null,
        NFT_LOG_MSG: null,
        TRACKING_ID: null,
        TAX_CLEARING_CERT_NO: null,
        TRADE_MEMBERSHIP_CERT_NO: null,
        IRC_NO: null,
        ERC_NO: null,
        LIST_SMS_NFT_AUTHORZ_LOG: [],
        LIST_COR_CUS_TRADE_BANK_INFO: [],
        LIST_COR_CUS_TRADE_INFO: [],
        LIST_SMS_NFT_AUTHORZ_LOG_LIEN_BANK: [],
        BONDED_W_LICENSE_NO: null,
        BONDED_W_LICENSE_ISSUE_DT: null,
        BONDED_W_LICENSE_EXP_DT: null,
        BONDED_W_LICENSE_LIEN_WITH: null,
        IRC_RENEWAL_AMT_FROM: null,
        IRC_RENEWAL_AMT_TO: null,
        IRC_RENEWAL_DATE_FROM: null,
        IRC_RENEWAL_DATE_TO: null,
        BONDED_W_RENEWAL_DT_FROM: null,
        BONDED_W_RENEWAL_DT_TO: null,
        TRADE_LICENSE_RENEW_DT_TO: null,
        TRADE_LICENSE_RENEW_DT_FRM: null,
        RENEWAL_NO: null,
        BONDED_W_LIEN_BANK: null,
        BONDED_W_LIEN_BRANCH: null,
        EDF_TOTAL_LIMIT: null,
        EDF_UTILIZED_LIMIT: null,
        EDF_ISSUE_DT: null,
        EDF_EXP_DT: null,
        EDF_RIM_LIMIT: null,
        EDF_ALLOW_CURRENCY_ID: null,
        IRC_ISSUE_DATE: null,
        STATUS: null,
        ADDRESS1: null,
        ADDRESS2: null,
        CITY: null,
        ZIP_CODE: null,
        DISTRICT_LGID: null,
        STATE_LGID: null,
        COUNTRY_ID: null,
        THANA_TR: null,
    },
    customerRiskRating: {
        CUSTOMER_ID: null,
        GROUP_ID: null,
        PROFILE_TYPE_ID: null,
        CUSTOMER_NM: null,
        BORROWER_ID_CIB: null,
        RISK_GRADE_METHOD_FLAG: null,
        RISK_GRADE_ID: null,
        LRA_METHOD_FLAG: null,
        LRA_BUSINESS_RISK_CAT_ID: null,
        LRA_SECURITY_RISK_CAT_ID: null,
        LRA_OVERALL_RISK_CAT_ID: null,
        LRA_Y_SCORE_NO: null,
        LRA_Z_SCORE_NO: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        AUTH_STATUS_ID: null,
        LAST_ACTION: null,
        ROWID: null,
        NFT_LOG_MSG: null,
        IS_EXTERNAL_RATING_FLAG: null,
        RATING_COMPANY_ID: null,
        RATING_GRADE_CODE: null,
        EXPOSURE_TYPE_ID: null,
        ECON_PURP_SBS_ID: null,
        ECON_PURP_CIB_ID: null,
        KEY_PERSON_NAME: null,
        KEY_PERSON_DESIG: null,
        KEY_PERSON_PHONE: null,
        LON_FINANCE_SECTOR_ID: null,
        INT_RISK_GRADE_ID: null,
        ERR_MSG: null,
        EXP_RATING_DT: null,
        BB_RATING_GRADE_ID: null,
        REPORTING_DATE: null,
        TRACKING_ID: null,        
	    LIST_SMS_NFT_AUTHORZ_LOG: null,
    },
    customerMasterAcc: {
        CUSTOMER_ID: null,
        CUSTOMER_NM: null,
        BRANCH_ID: null,
        BRANCH_NM: null,
        ACCOUNT_NO: null,
        ACCOUNT_TITLE: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        AUTH_2ND_BY: null,
        AUTH_2ND_DT: null,
        AUTH_STATUS_ID: null,
        LAST_ACTION: null,
        ROWID: null,
        NFT_LOG_MSG: null,
        ERROR_MSG: null,
        TRACKING_ID: null
    },
    cusBusAddress:{
        CUSTOMER_ID: null,
        ADDRESS1: null,
        ADDRESS2: null,
        CITY: null,
        ZIP_CODE: null,
        THANA_LGID: null,
        DISTRICT_LGID: null,
        STATE_LGID: null,
        COUNTRY_ID: null,
        PHONE: null,
        FAX: null,
        TELEX: null,
        SWIFT: null,
        EMAIL: null,
        WEB: null,
        CONTACT_PERSON_NM: null,
        CONTACT_PERSON_DESIG: null,
        CONTACT_PERSON_PHONE: null,
        CONTACT_PERSON_MOBILE: null,
        CONTACT_PERSON_EMAIL: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        LAST_ACTION: null,
        ROWID: null,
        NFT_LOG_MSG: null,
        MOBILE2: null,
        PHONE2: null,
        MOBILE: null,
        TRACKING_ID: null,
        LIST_SMS_NFT_AUTHORZ_LOG: []
    },
    corCusTradeBankInfo: {
        CUSTOMER_ID: null,
        LIEN_BANK_ID: null,
        LIEN_BRANCH_ID: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        AUTH_2ND_BY: null,
        AUTH_2ND_DT: null,
        AUTH_STATUS_ID: null,
        LAST_ACTION: null,
        BANK_NM: null,
        BRANCH_NM: null,
        CUST_NM: null,
        ROWID: null,
        TRACKING_ID: null,
        SL_NO: null,
        STATUS: null,
        LIST_SMS_NFT_AUTHORZ_LOG: null,
    },
    corCusAssociAcc: {
        CUSTOMER_ID: null,
        BRANCH_ID: null,
        BRANCH_NM: null,
        ACCOUNT_NO: null,
        ACCOUNT_TITLE: null,
        MAKE_BY: null,
        MAKE_DT: null,
        AUTH_1ST_BY: null,
        AUTH_1ST_DT: null,
        AUTH_2ND_BY: null,
        AUTH_2ND_DT: null,
        AUTH_STATUS_ID: null,
        LAST_ACTION: null,
        ROWID: null,
        NFT_LOG_MSG: null,
        TRACKING_ID: null,
        STATUS: null,
    }
};

const state = {
    customerInfo: {...customerInfoData }
}

const getters = {
    // customer: state => {
    //     return state.customerInfo;
    // }
}


const mutations = {
    setCustomerInfo(state, customerInfo) {
        state.customerInfo = customerInfo;
        // console.log(this.$store.state.customer.customerInfo.customerProfileData);
    },
    resetCustomerlistinfo(state) {
        state.customerInfo = {...customerInfoData };
    },
    setOtherInfo(state, { MAKE_BY, MAKE_DT, AUTH_1ST_BY, AUTH_1ST_DT, LAST_ACTION }) {
        
    }
};

const actions = {
    // changeCustomer (context, payload) {
    //     setTimeout(() => {
    //       context.commit("changeCustomer", payload);
    //     }, 2000);
    //   }
}

export default {
    state,
    getters,
    actions,
    mutations
};